### ISSUE TITLE
Spitfire Error on Feed page

### ISSUE THREAD

**Issue by DmitriySaliy** [Csardelacal/ping#17]
Got an error on URL: https://ping.commishes.com/feed/

Stack trace for "Error 42000 [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND `ping_ping`.`processed` = '1' AND `ping_ping`.`deleted` IS NULL AND `ping_' at line 1] captured. Not repairable"

![image](https://user-images.githubusercontent.com/32593374/166828945-aa48fa01-2605-44e5-adbd-6bd993564f93.png)

**Comment by Csardelacal** [comment]
Hey there Dmitriy, thanks for reporting this issue. I've been playing around with a bit of code that was giving another user trouble. I have now reverted the change. Is it back to normal for you?

**Comment by DmitriySaliy** [comment]
Yes, thanks
